homepage:
  path: /
  defaults: { _controller: BlogBundle:Blog:teaser }
blog_teaser:
  path: /blog/
  defaults: { _controller: BlogBundle:Blog:teaser }
blog_about_us:
  path: /about_us/
  defaults: { _controller: BlogBundle:Page:aboutUs }
blog_view:
  path: /blog/{id}
  defaults: { _controller: BlogBundle:Blog:blogView }
  requirements :
    id: \d+